networks:
  easyfish:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.128.0.0/16
volumes:
  db_data:

services:
  db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      easyfish:
        ipv4_address: 172.128.0.200

  backend:
    build: "https://github.com/kruceo/easyfish.git#main:backend"
    command: ["/bin/sh","-c","sleep 10s && ./start.sh"]
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - CORS_ORIGIN=http://localhost,http://localhost:5173,http://172.128.0.202
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_SCHEMA=principal
      - DB_HOST=172.128.0.200
      - DB_PORT=5432
      - DB_DIALECT=postgres
      - SECRET=otherexample
    depends_on:
      - db
    networks:
      easyfish:
        ipv4_address: 172.128.0.201

  frontend:
    build: "https://github.com/kruceo/easyfish.git#main:frontend"
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - DOMAIN=localhost
      - API_ADDRESS=localhost
      - API_PROTOCOL=http
      - API_PORT=8080
      - PRINTER_PROTOCOL=http
      - PRINTER_ADDRESS=localhost
      - PRINTER_PORT=8888
    depends_on:
      - backend
    networks:
      easyfish:
        ipv4_address: 172.128.0.202

  thermal:
    build: https://github.com/kruceo/thermal-printer.git
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
      - PRINTER_VENDOR=EPSON
      - PRINTER_NAME=TM-T20X
      - PRINTER_WIDTH=48
      - PRINTER_CHARSET=WPC1254_Turkish
    devices:
      - "/dev/bus/usb"
    depends_on:
      - frontend
    networks:
      easyfish:
        ipv4_address: 172.128.0.203