name: Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: docker compose build frontend backend
    
    - name: Setup Backend
      run: timeout 30s docker compose up backend db || [[ $? -eq 124 ]] && exit 0

    - name: Setup Frontend
      run: timeout 30s docker compose up frontend backend db || [[ $? -eq 124 ]] && exit 0

    - name: Setup All
      run: docker compose up -d frontend backend db
    
    - name: Test Backend
      run: sleep 30 && curl -f http://localhost:8080/status
    
    - name: Test Frontend
      run: sleep 60 && curl -f http://localhost/login
      
